### ISSUE TITLE
fftw3 needs double precision

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#10]
ISMRMRD only needs single precision libraries for FFTW3 but Gadgetron needs both single and double.

This might need 2 builds for fftw (so in different locations). See 
http://www.fftw.org/fftw2_doc/fftw_6.html
However, not sure if the type-prefix is what we need.

**Comment by KrisThielemans** [comment]
easiest solution might be as follows:

create 2 external projects: FFTW3single, FFTW3double. Identical aside from the "--enable-float" flag. Let ismrmrd depend on FFTW3single, and gadgetron on both.

@bathomas, @paskino what do you think?

**Comment by KrisThielemans** [comment]
I've checked that the *.h files are identical in both installations, so that's ok.

It implies downloading the package twice, but I don't care...

**Comment by paskino** [comment]
agreed, I'm doing it.

**Comment by KrisThielemans** [comment]
fixed in fa02925d50593df917b1a09c4731bc4a53207669
