### ISSUE TITLE
Install the Python modules with setup.py

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#107]
Currently the compiled Python modules are installed into a directory, `PYTHON_DEST`, which must be prepended to `PYTHONPATH`.

Modules are loaded as 
```python
import pGadgetron
import pStir
...
``` 
and it all goes fine. However, we should really be creating a `sirf` package, which can fit into a `site-packages` structure (system or conda). The consequence is that imports will look different

```python
from sirf import pGadgetron
from sirf import pStir
...
```

**Comment by casperdcl** [comment]
This would be backward-incompatible. We could provide separate `pGadgetron` and `pStir` packages which depend on each other. We could also make these aliases for `sirf.pGadgetron`/`pStir`, thus remaining backward-compatible

**Comment by KrisThielemans** [comment]
Note that this should probably be a SIRF issue as well. (Should there be a `setup.py` in SIRF?) Similar STIR issue is https://github.com/UCL/STIR/issues/5. 

Note that this won't solve the problem of needing to set the `LD_LIBRARY_PATH` (or a similar variable for your OS) to find shared libraries at run-time.

**Comment by casperdcl** [comment]
Actually setup.py can handle that too (if by shared libs you mean the swig-generated python ones eg _py*.so)

**Comment by KrisThielemans** [comment]
great, but also gadgetron, ismrmrd, boost, ...

**Comment by KrisThielemans** [comment]
@paskino,@casperdcl, this issue can be closed?

**Comment by casperdcl** [comment]
closed by https://github.com/CCPPETMR/SIRF/pull/163 (related: #109, #112)
