### ISSUE TITLE
FindMKL.cmake

### ISSUE THREAD

**Issue by ashgillman** [CCPPETMR/SIRF-SuperBuild#108]
Hi,

I am having an issue with building the Super Build:

 ```
CMake Warning at SuperBuild/External_Gadgetron.cmake:53 (find_package):
   By not providing "FindMKL.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "MKL", but
   CMake did not find one.

   Could not find a package configuration file provided by "MKL" with any of
   the following names:

     MKLConfig.cmake
     mkl-config.cmake

   Add the installation prefix of "MKL" to CMAKE_PREFIX_PATH or set "MKL_DIR"
   to a directory containing one of the above files.  If "MKL" provides a
   separate development package or SDK, be sure it has been installed.
 Call Stack (most recent call first):
   CMake/ExternalProjectDependency.cmake:593 (include)
   CMake/ExternalProjectDependency.cmake:639 (ExternalProject_Include_Dependencies)
   SuperBuild.cmake:154 (ExternalProject_Include_Dependencies)
   CMakeLists.txt:18 (include)
```

Is MKL a required or optional dependency of Gadgetron? Should the SuperBuild automatically install MKL (and I am just missing the FindMKL.cmake, perhaps this one https://github.com/gadgetron/gadgetron/blob/master/cmake/FindMKL.cmake), or should I have this installed before running the SuperBuild?

Many thanks,
Ash

**Comment by KrisThielemans** [comment]
MKL is an optional dependency of Gadgetron. We cannot install it as you need to sign-up with Intel to get a license.

However, the error above is saying that Gadgetron couldn't find its own FindMKL.cmake, which is entirely weird. Can you check if it is in `whereveryoubuild/sources/Gadgetron/cmake`? (should be  about 10 other files there as you can see).

Where are you building? How did you configure your SIRF-SuperBuild? (`DEVEL_BUILD` by any chance?)

**Comment by ashgillman** [comment]
Actually, I apologise. It appears the above is only a warning not an error. After running the `ccmake` configure step twice, I was still able to generate the Makefile.

But, I do believe that for anyone without Gadgetron already installed, they will get this warning as they won't yet have a FindMKL.cmake.
