### ISSUE TITLE
export GADGETRON_HOME in env_ccppetmr.*

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#115]
newest Gadgetron needs the GADGETRON_HOME environment variable, see https://github.com/CCPPETMR/SIRF/issues/158.

**Comment by paskino** [comment]
[Apparently ](https://github.com/gadgetron/gadgetron/wiki/Linux-Installation)`GADGETRON_HOME` is the install directory.
