### ISSUE TITLE
PRs fail on travis due to trouble with the stats

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#119]
I created a PR from my own fork (#118). All jobs are failing due to time-out because an infinite loop
```
remote: Anonymous access to ccp-petmr-codebot/github-stats.git denied.
fatal: Authentication failed for 'https://@github.com/ccp-petmr-codebot/github-stats/'
```
see for instance https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/378186880

2 problems with this: it fails, and it creates an infinite loop. :-(

Not sure if this is a temporary travis problem. I'll accept the PR and see...

**Comment by casperdcl** [comment]
Oh interesting. A Travis environment issue. I can see why they would choose to do this, it's for security. Right, I'd need to change this so the stats logic can fail silently, I suppose. Hmm. Also it's still overcounting, but at least in a way that I can work out by how much and fix it in future. Still can't think of a way around avoiding counting builds which fail before they get to the stats logic, though

**Comment by KrisThielemans** [comment]
@casperdcl [this is still happening](https://api.travis-ci.org/v3/job/411795270/log.txt) I'm afraid.

**Comment by casperdcl** [comment]
oh hey time to have another look
