### ISSUE TITLE
Travis fails on OSX with boost

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#133]
````
Error: boost 1.67.0_1 already installed
```
presumably caused by
```
brew upgrade boost
```
it's criminal that this causes an error. @DANAJK, @bathomas, @rijobro, any suggestions (aside from commenting out the line again)

**Comment by rijobro** [comment]
Could we do `brew reinstall boost`? That way, we'll always have the most recent version without the error (although commenting it out would presumably have the same effect).

**Comment by KrisThielemans** [comment]
[Example log file](https://api.travis-ci.org/v3/job/413160775/log.txt)

**Comment by KrisThielemans** [comment]
Is this normal brew behaviour, or something specific to boost, or specific to Travis? i.e. can someone with OSX try a few `brew update` commands?

**Comment by rijobro** [comment]
I get the same error when I run `brew upgrade boost` and I already have the most recent version. I'll try with `brew reinstall boost`.

**Comment by KrisThielemans** [comment]
reinstall will take a fair amount of time presumably. Ideally we'd do a version check in travis, but that seems [complicated enough in brew](https://discourse.brew.sh/t/where-to-get-version-number/627/7). I'll comment this out for now.

I've created #135 to at least fall over if the boost version is wrong.

**Comment by rijobro** [comment]
It only takes a few seconds because it's already downloaded:
```
==> Reinstalling boost 
==> Downloading https://homebrew.bintray.com/bottles/boost-1.67.0_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/travis/Library/Caches/Homebrew/boost-1.67.0_1.high_sierra.bottle.tar.gz
==> Pouring boost-1.67.0_1.high_sierra.bottle.tar.gz
/usr/local/Cellar/boost/1.67.0_1: 13,506 files, 451.0MB
```
This means we'll either get the new version or, if the new version is already installed, reinstall it without downloading it.

With this, tests are now advancing past the point they were previously crashing. Is that not OK?

**Comment by KrisThielemans** [comment]
not sure if `reinstall` would actually get the new version (i.e. upgrade). Sounds to me like it wouldn't. If so, there's no point in doing it as far as I can see. In any case, could you create a PR with the best solution? Some Travis jobs will still fail because of the other issues, but at least some of the OSX ones should go through. Then let me know when it's ready to accept.

**Comment by paskino** [comment]
maybe the same as https://github.com/CCPPETMR/SIRF/pull/201 should work?

**Comment by KrisThielemans** [comment]
indeed. we need the fix in both SIRF and SIRF-SuperBuild. unfortunate duplication. @paskino, can you accept CCPPETMR/SIRF#201 after review and put the same in the SIRF-SuperBuild?
