### ISSUE TITLE
Pin DEVEL_BUILD to recent gadgetron

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#134]
Gadgetron master is tripping us up rather regularly unfortunately. I feel we should fix `DEVEL_BUILD=On` to use a specific (but recent) gadgetron version as opposed to its master. We can then update the `GADGETRON_TAG` occasionally via a SIRF-SuperBuild PR. Any objections?

we could do the same for STIR if it becomes necessary.

**Comment by KrisThielemans** [comment]
We're now getting failures on `DEVEL_BUILKD`
```
CXX COMPILER VERSION: GNU : 4.8.4
CMake Error at CMakeLists.txt:43 (message):
  Gadgetron requires GCC version >= 6.0
```
that'll be fun on travis etc.

In any case, this reinforces the motivation for doing the above. @DANAJK @ckolbPTB @johannesmayer  any objections? Please suggest a commit if you can

**Comment by DANAJK** [comment]
I have no objections. Unfortunately I cannot suggest a specific commit for Gadgetron.

**Comment by KrisThielemans** [comment]
see #146
