### ISSUE TITLE
upgrade Gadgetron and ISMRMRD

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#146]
New Gadgetron needs gcc 6.0 and newer ISMRMRD. See previous discussion at #145.

Ubuntu 16.04 has 5.4. On the VM it could be possible to install gcc version 6 following [this link](https://askubuntu.com/questions/746369/how-can-i-install-and-use-gcc-6-on-xenial/746480)

@paskino sees a few options:

1. Build a new VM with [Ubuntu 18.04](https://app.vagrantup.com/ubuntu/boxes/bionic64) which ships [GCC 7.3.0](https://packages.ubuntu.com/bionic/gcc) 
2. Add the new unofficial repository to get GCC 6 onto the current VM (Ubuntu 16.04)
3. Use conda
4. Keep outdated Gadgetron in the short term.

Although option 3 is still in a [work-in-progress](https://github.com/CCPPETMR/SIRF-SuperBuild/pull/112) phase @paskino strongly believes that we should pursue that direction.

_Originally posted by @paskino in https://github.com/CCPPETMR/SIRF-SuperBuild/pull/145#issuecomment-426936012_

**Comment by KrisThielemans** [comment]
>  Build a new VM with Ubuntu 18.04 which ships GCC 7.3.0

I see no reason not to do this. we'll have to move on soon anyway.

>   Add the new unofficial repository to get GCC 6 onto the current VM (Ubuntu 16.04)

A pain. I'd like to avoid it. 

>    Use conda

I don't see how conda is going to help avoiding having to use gcc 6 for gadgetron.

>  Keep outdated Gadgetron in the short term.

As we're moving to SIRF 2.0, it's a good time to upgrade Gadgetron. So I wouldn't do that.

**Comment by KrisThielemans** [comment]
@dchansen, @xueh2 what would a good Gadgteron, and ISMRMRD commit be?

**Comment by paskino** [comment]
conda can help by being able to install specific compilers?

**Comment by dchansen** [comment]
For gadgetron we're currently using both 1 and 2.
We're moving to Ubuntu 18.04 as soon as everything (non-Gadgetron) works on the scanner side, and in the meantime we've upgraded our docker images with GCC 6.

**Comment by KrisThielemans** [comment]
@dchansen, sorry, not sure what you mean with 
> For gadgetron we're currently using both 1 and 2.

**Comment by KrisThielemans** [comment]
> conda can help by being able to install specific compilers?
yeah, but who's going to do that, aside from you?

**Comment by casperdcl** [comment]
I agree you probably don't want to conda install a compiler if you can avoid it - if people conda install into their default conda environment, they'll get the new compiler overriding their system one in that environment without necessarily realising.

**Comment by paskino** [comment]
@KrisThielemans  it's not so trivial to install a different compiler with conda. Though conda provides [new compilers](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html) (only for Mac and Linux), conda-forge is not currently using those.

**Comment by paskino** [comment]
@casperdcl the compiler is requested only for the build (possibly)

**Comment by bathomas** [comment]
I agree with @KrisThielemans, I think using conda in this way is asking for trouble.

**Comment by paskino** [comment]
OK, I'll proceed with option 1.

**Comment by KrisThielemans** [comment]
@rijobro you're working on this. It's quite tricky though. Please refer to this issue with your updates and comment.

**Comment by rijobro** [comment]
external fix required (PR on gadgetron: https://github.com/gadgetron/gadgetron/pull/726). 

Once this is done, should be ok to update.

**Comment by KrisThielemans** [comment]
Done in #205
