### ISSUE TITLE
env_ccppetmr.csh uses wrong syntax

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#159]
there's an `endif` in there

**Comment by paskino** [comment]
I'm no expert in csh, but it seems `endif` is needed in [csh if statements](https://en.wikipedia.org/wiki/C_shell#if_statement).

**Comment by KrisThielemans** [comment]
sorry. message was confusing and I was in a hurry
```
% source INSTALL/bin/env_ccppetmr.csh
else: endif not found.
```
The problem is a missing `endif` after the `PYTHONPATH` setting.

You can try this on the VM by in a terminal and then doing the `csh ...INSTALL/bin/env_ccppetmr.csh`, or (once fixed)  just typing `csh` and then `source ...INSTALL/bin/env_ccppetmr.csh`

**Comment by rijobro** [comment]
done with 8e91546ad7fa8044f457f35b26c2b9f38da86743.
