### ISSUE TITLE
make location of output of SuperBuild consistent

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#16]
some projects (probably CMake-ones) have their build in `x-prefix/src/x-build` as opposed to `x-build`.

Also, INSTALL is currently hard-wired but should honour `CMAKE_INSTALL_PREFIX`.

**Comment by paskino** [comment]
indeed the default location for external projects is 

> If no PREFIX, EP_PREFIX, or EP_BASE is specified then the default is to set PREFIX to <name>-prefix. Relative paths are interpreted with respect to the build directory corresponding to the source directory in which ExternalProject_Add is invoked.

TMP_DIR      = <prefix>/tmp
STAMP_DIR    = <prefix>/src/<name>-stamp
DOWNLOAD_DIR = <prefix>/src
SOURCE_DIR   = <prefix>/src/<name>
BINARY_DIR   = <prefix>/src/<name>-build
INSTALL_DIR  = <prefix>

So far we only force the source directory to be <name> and contained in the build directory. 
A better option IMO would be to have:

```
devel/
         -> sources
         -> builds
         -> install
```

https://cmake.org/cmake/help/v3.7/module/ExternalProject.html?highlight=EP_BASE

**Comment by KrisThielemans** [comment]
yes. This not a bad idea. It will be potentially somewhat confusing/dangerous though to have the superbuild build in
```
devel/builds/SIRG-SuperBuild
```
but writes its sources in 
```
devel/sources/SIRF
```
etc. We certainly cannot have that by default in the SuperBuild. We could have a new CMake variable `SRC_INSTALL_DIR` ? Then on the VM or Docker we can set that according to your suggestion.

I also agree with your `install` suggestion, but again we can't have that by default in the SuperBulid. Let's fix this as in the VM. https://github.com/CCPPETMR/CCPPETMR_VM/issues/35

By the way, there is some confusion between all these `ExternalProject_Add` variables as some of them are used when using git, while others are used for the download-binaries, and others are used for the download-source cases (or at least I think so, as that's why there is currently a difference between e.g. `SIRF` and `HDF5`.

I'd be happy to just fix this for the git ones for now. we can fit the rest later.

**Comment by KrisThielemans** [comment]
On VM, target will be something like
```
devel/SuperBuildFiles
         -> sources
         -> builds
devel/install
```

**Comment by paskino** [comment]
I believe this is already implemented.

**Comment by KrisThielemans** [comment]
not really done. Example: SIRF source sits in the root-dir, but its actual build sit in `SIRF-prefix/src/SIRF-build` (not very logical). For non-CMake packages, this is different again.

**Comment by KrisThielemans** [comment]
proposed structure:
- `sources`
    - `SIRF`
    - `STIR`
- ` builds`
    - `SIRF`
       - ` build`
       - ` stamp`
       - `tmp`
    - `STIR`
- `install`

**Comment by paskino** [comment]
I believe we could specify [`EP_BASE`](https://cmake.org/cmake/help/v3.7/module/ExternalProject.html?highlight=EP_BASE)
> if  the EP_BASE directory property is set then components of an external project are stored under the specified base:

```
TMP_DIR      = <base>/tmp/<name>
STAMP_DIR    = <base>/Stamp/<name>
DOWNLOAD_DIR = <base>/Download/<name>
SOURCE_DIR   = <base>/Source/<name>
BINARY_DIR   = <base>/Build/<name>
INSTALL_DIR  = <base>/Install/<name>
```

**Comment by paskino** [comment]
Are you happy with this structure? If so it's one line of change.

**Comment by paskino** [comment]
Well, it seems CMake isn't quite doing what I thought. 

The structure in the build directory is a mess and this is the content of the Build Install Stamp Download tmp directories. Notice that Source doesn't exist and the sources are in the build directory :(

```
Download/
                 Armadillo  
                 FFTW3
                 Gadgetron  
                 HDF5
                 SIRF
                SWIG
                Boost
                FFTW3double
                GTest
               ISMRMRD
               STIR
Install/
          Armadillo
          Boost  
          FFTW3  
          FFTW3double  
          HDF5  
          SWIG
Build/
         Gadgetron  
         GTest  
         ISMRMRD  
         SIRF  
         STIR
Stamp/
           Armadillo  
           FFTW3          
           Gadgetron    
           HDF5       
           SIRF    
           SWIG  
           Boost        
           FFTW3double    
           GTest        
           ISMRMRD    
           STIR
tmp/
       Armadillo  
       FFTW3        
       Gadgetron          
       HDF5             
       SIRF          
       SWIG        
       Boost              
       FFTW3double          
       GTest              
       ISMRMRD          
       STIR
./
Armadillo            
CTestTestfile.cmake  
GTest           
SIRF
Armadillo-build      
FFTW3                
GTest-prefix    
SIRF-prefix
Armadillo-prefix     
FFTW3-build          
HDF5            
STIR
Boost                
FFTW3double          
HDF5-build      
STIR-prefix
Boost-build          
FFTW3double-build    
HDF5-prefix     
SWIG
Boost-prefix         
FFTW3double-prefix  
 ISMRMRD        
 SWIG-build
CMakeCache.txt      
 FFTW3-prefix         
ISMRMRD-prefix  
SWIG-prefix
CMakeFiles           
Gadgetron           
 Makefile
cmake_install.cmake  
Gadgetron-prefix     
Matlab
        
   
```

**Comment by KrisThielemans** [comment]
oh well... I wonder if some of these are left-overs from a previous build though. not sure

**Comment by paskino** [comment]
with https://github.com/CCPPETMR/SIRF-SuperBuild/commit/f255b459fafab9d304df225c77db2a68c75b5855 I have set the build directories as [proposed](https://github.com/CCPPETMR/SIRF-SuperBuild/issues/16#issuecomment-360772097)

I have a problem about `ctest` which picks the wrong `data` directory.

**Comment by KrisThielemans** [comment]
I've seen somewhere in the doc a reference to where the examples are etc, but I cannot find it anymore. In any case, this should be somehwere rather promiment. It's going to change with this PR, so put it in the README.md I think.

**Comment by KrisThielemans** [comment]
On Windows I use binary downloads for SWIG and FFTW. I notice that these get put in e.g. 
`build/SWIG-prefix/src/swigwin-3.0.12.zip` and extracted into `build/SWIG-prefix/src/SWIG`. Arguably the zip file should go into `downloads`, and the extracted binaries into `builds` or also `downloads` (In prniciple, they could be extracted directly in the install location, but I don't think we can do that an dI don't really care).

Note also that currently `downloads` contains e.g. `SIRF`, `STIR` etc empty subdirs. That doesn't really bother me either.

**Comment by KrisThielemans** [comment]
sorry. could you please assign somebody else, pr be preated to wait :-;

**Comment by paskino** [comment]
Who else is installing on Windows?

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov, you're not using the superbuild yet, but this would be good to try. Not urgent though
