### ISSUE TITLE
Link to static boost libraries

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#163]
Rationale: https://github.com/CCPPETMR/SIRF/issues/241

Method: Add `-DBoost_USE_STATIC_LIBS=ON` to the `CMAKE_ARGS` for Gadgetron, ISMRMRD and SIRF, at least if we build Boost ourselves, or after checking if the system boost has the static libraries.

**Comment by KrisThielemans** [comment]
[Failure for ISMRMRD](https://github.com/ismrmrd/ismrmrd/issues/114) but the library doesn't use boost, so this isn't a show-stopper.

Therefore, we really only need this for SIRF. Easy enough to try.

**Comment by evgueni-ovtchinnikov** [comment]
both on VM and augrabies .cs.ucl.ac.uk got error
'''
/usr/bin/ld: /home/sirfuser/devel/install/lib/libboost_thread.a(thread.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
'''
find it hard to believe boost libraries compiled without `-fPIC`
