### ISSUE TITLE
OSX: CMake fails to detect version of brew HDF5

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#168]
When using `USE_SYSTEM_HDF5=ON` on OSX, [we get](https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/465481883)
```
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HDF5: Found unsuitable version "", but required is at least
  "1.8" (found HDF5_hdf5_LIBRARY-NOTFOUND)
```
This does not occur when building our own HDF5 (v1.10.1). OSX 10.13.3, brew HDF5 claims to be 1.8.

**Comment by KrisThielemans** [comment]
@rijobro, could you check this with recent `CMake` and `brew` and update accordingly? The only thing we can do is to document it on the Wiki. After that's done, please close this.

**Comment by rijobro** [comment]
I use `Brew` installed HDF5 and don't have any problems. Not sure how you want me to document this.

**Comment by KrisThielemans** [comment]
what version of HDF5 does `brew` currently install? If it's still 1.8, then presumably your CMake is more recent than 3.11.4. We should then either require CMake 3.12 on OSX, or put it in the wiki that `USE_SYSTEM_HDF5=ON` might fail with CMake version 3.11 (or presumably earlier)

**Comment by rijobro** [comment]
current version installed by `brew` is `1.10.4`. Will update the wiki for the CMake version.

**Comment by rijobro** [comment]
instruct users to use >=3.12 here: https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-on-MacOS
