### ISSUE TITLE
travis improvements

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF-SuperBuild#17]
- [x] Put the Travis link on the SIRF github site
- [x] Put the Travis link on the SuperBuild github site
- [x] Sort-out the Travis ‘matrix’ when enabling both Linux and osx
- [x] Trigger the Travis build when SIRF (or other CCPPETMR forks) changes.
(see [SIRF#69](https://github.com/CCPPETMR/SIRF/pull/69), [SIRF#71](https://github.com/CCPPETMR/SIRF/pull/71))

**Comment by casperdcl** [comment]
From @KrisThielemans' email:

Dear all

 

I’ve spent quite a few painful hours to get TravisCI  up and running for SIRF (using the SuperBuild).

 

For those who don’t know Travis, I’ve attached a nice email from David Volgyes to the STIR list when he enabled it for STIR. It applies verbatim to SIRF. This means that I have quite a lot of confidence in SIRF and the superbuild to work on Linux. And of course, whenever do a commit to the SuperBuild, the tests gets run automatically.

 

It was a bit complicated to get this to work for SIRF due to its many dependencies and the fact that Travis on Linux uses “trusty” (i.e. Ubuntu 14.04) which is too old. I had therefore to put in extra bits to get a new CMake, use gcc-5 and add some extra version checks. Also, it enabled me to find and fix a number of bugs. The hardest one was a weird problem when using USE_SYSTEM_* (see https://github.com/CCPPETMR/SIRF-SuperBuild/commit/3a07d997897fbadae74c74164b5b7dc03ba2e0f8).

 

Current test include building SIRF and Gadgetron and running the 3 automatic tests that we have:

  - ./SIRF/src/xSTIR/pSTIR/tests/test1.py

  - ./SIRF/src/xGadgetron/pGadgetron/tests/fully_sampled.py

  - ./SIRF/src/xGadgetron/pGadgetron/tests/undersampled.py

 

The good news is that this now works fine for Linux (trusty) (tested with gcc-5, python 2.7 and 3.0, a few combinations of SYSTEM and self-built packages). The test for MacOSX still failed 10 mins ago and is still running.

 

You can see the Travis builds and logs at https://travis-ci.org/CCPPETMR/SIRF-SuperBuild. The master branch should now always be green…

**Comment by KrisThielemans** [comment]
I've added the Travis link in the SIRF-Superbuild README.md. Would be best to add to SIRF as well.

**Comment by casperdcl** [comment]
looks like this is almost ready, then? Just need the badge on SIRF?

**Comment by KrisThielemans** [comment]
Not sure how the 2 last boxes (travis matrix and build triggering) got ticked. That I do that by mistake? (This seems a problem with the todo-list. there seems no way to find out when/why they get ticked by who).

Please untick unless you know better...

**Comment by casperdcl** [comment]
Hi Kris, yes - you can't tell when things get ticked/unticked. I thought the last two were complete so ticked them. Haven't actually looked at the .travis.yml file or configuration so don't know. Unticked now.

**Comment by KrisThielemans** [comment]
Seems that the straightforward extension (640383c4b4a1e82e5b951da806002902a80b45a1) of using python on osx doesn't work. Message is the same as
https://github.com/travis-ci/travis-ci/issues/4729, which leads to a link with some helpful suggestions at the bottom, which is our current strategy.

**Comment by KrisThielemans** [comment]
On OSX with default compiler, we currently get (with `USE_SYSTEM_BOOST=On`)
```
In file included from /Users/travis/build/CCPPETMR/SIRF-SuperBuild/Gadgetron/toolboxes/python/python_toolbox.cpp:11:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:22:
/usr/local/include/boost/thread/pthread/timespec.hpp:79:12: error: no member named 'clock_gettime' in the global namespace; did you mean 'ACE_OS::clock_gettime'?
      if ( ::clock_gettime( CLOCK_MONOTONIC, &ts ) )
           ^~
/usr/local/include/ace/OS_NS_time.inl:58:9: note: 'ACE_OS::clock_gettime' declared here
ACE_OS::clock_gettime (clockid_t clockid, struct timespec *ts)
```
see https://api.travis-ci.org/jobs/282405991/log.txt?deansi=true.
boost version seems 1.65.1. This might be a new bug introduced in 1.64.0 (older versions explicitly didn't use this line, see e.g. http://www.boost.org/doc/libs/1_63_0/boost/thread/pthread/timespec.hpp).

**Comment by KrisThielemans** [comment]
The remaining major issues (about SIRF) will be fixed by https://github.com/CCPPETMR/SIRF/pull/69. so this could be closed once that is merged.

**Comment by KrisThielemans** [comment]
Currently OSX builds fail again as pip is no longer installed in the system python. I'm trying to fix this for STIR https://github.com/UCL/STIR/pull/127, so let's wait for that.

@bathomas  @rijobro do you know if this is a Travis-specific issue, or do we need to update the installation instructions on the wiki?
