### ISSUE TITLE
No USE_SYSTEM_Gadgetron

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF-SuperBuild#188]
This option exists for most SIRF dependencies, but not Gadgetron. Is there a reason for this? 

Unfortunately, Gadgetron do not supply a `GadgetronConfig.cmake` file, so would we have to write our own to be able to have a `USE_SYSTEM_Gadgetron`?

**Comment by KrisThielemans** [comment]
we don't link with Gadgetron (currently), so don't need it. It'd be the same as `BUILD_Gadgetron=OFF`

**Comment by paskino** [comment]
I think there's a typo in the CMakeLists.txt and the variable is [`BUILD_GADGETRON`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild.cmake#L165)

**Comment by rijobro** [comment]
> we don't link with Gadgetron (currently), so don't need it. It'd be the same as BUILD_Gadgetron=OFF

Ah, I see. Thanks.

> I think there's a typo in the CMakeLists.txt and the option name is BUILD_GADGETRON

It might be a typo, but at least it's consisent in the code.
