### ISSUE TITLE
The option BUILD_GADGETRON should be BUILD_Gadgetron

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#189]
The name of the option [`BUILD_GADGETRON` ](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild.cmake#L165)should be `BUILD_Gadgetron` as the target name is `Gadgetron`.
See #188

**Comment by KrisThielemans** [comment]
@paskino can you do this with backwards compatibility? Call the option that way, but if the old one is set, use it to set the default for the new I guess.

**Comment by KrisThielemans** [comment]
```cmake
if (BUILD_GADGETRON)
  set(def_BUILD_Gadgetron ${BUILD_GADGETRON})
else()
  set(def_BUILD_Gadgetron ON)
endif()
option(BUILD_Gadgetron "" ${def_BUILD_Gadgetron})
```
