### ISSUE TITLE
Gadgetron unit test fails

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF-SuperBuild#193]
The Superbuild can now run the unit tests of the SIRF dependencies. However, the Gadgetron test is failing on OSX. It's failing on my machine due to a bug in BLAS (see [here](https://github.com/gadgetron/gadgetron/issues/719)), and I can only assume it's failing on Travis for the same reason. 

@KrisThielemans suggested using Docker to build Gadgetron on OSX. @casperdcl, is there any way you'd be able to give this a look? I successfully installed it on my machine with:
```
docker build --no-cache -t my_gadgetron_image /path/to/Gadgetron/Source/docker/incremental/ubuntu_1804_no_cuda
```
However, I'm an extreme Docker novice and I'm not sure how to run it after I've installed it (or where it installs to). Nor do I know if it's been compiled with testing on or off (how do I specify these sorts of things like I would in CMake?).

If you don't have access to a Mac, I can run any commands to test it out and then we can put it in to the `.travis.yml` file once we're happy (or you can go directly to the `.travis.yml` if you're feeling brave!).

**Comment by casperdcl** [comment]
Hi @rijobro - Once you've built the gadgetron docker image as you stated, you'd have to run it and expose its port:
```
docker run -e "GADGETRON_RELAY_HOST=<HOST IP/NAME>" -p 9002:9002 -a -i --rm -t my_gadgetron_image
```
where `<HOST IP/NAME>` should be replaced with your host machine's IP/name. Alternatively I'm pretty sure it can just be `0.0.0.0` though.

You should then be able to run tests in another terminal

**Comment by rijobro** [comment]
Thanks for the help. I just ran the command but an error was returned:
```
invalid argument "-i" for "-a, --attach" flag: valid streams are STDIN, STDOUT and STDERR
```

**Comment by casperdcl** [comment]
oops without the `-i`

**Comment by casperdcl** [comment]
If you want to edit build options, you need to edit: `/path/to/Gadgetron/Source/docker/incremental/ubuntu_1804_no_cuda/Dockerfile` and build the image again (I'd leave out the `--no-cache` flag to make things faster).

**Comment by rijobro** [comment]
So to start, I do: 
```
docker run -e "GADGETRON_RELAY_HOST=<0.0.0.0>" -p 9002:9002 --rm -t my_gadgetron_image
```
Then I should be able to open a new terminal window and type `gadgetron`?

Finally, what's the command to stop it again? I tried with no luck:
```
docker stop my_gadgetron_image
```

**Comment by casperdcl** [comment]
I'd just `Ctrl`+`C` out of the gadgetron terminal to stop. You can always run `docker ps` to find the randomly generated name of the running container for use in the `docker stop` command. You can also assign a name when you run: `docker run ... -t gtron` will allow `docker stop gtron`

**Comment by rijobro** [comment]
Ok, this is slowly starting to make sense. Once I've done `docker run my_gadgetron_image`, how can I then launch `gadgetron`? Normally after installing `gadgetron` you need to do something like:
```
mv Gadgetron-install-dir/share/gadgetron/config/gadgetron.xml.example Gadgetron-install-dir/share/gadgetron/config/gadgetron.xml
```
Do I need to do that in this case? If so, I need to know where docker installs everything.

**Comment by rijobro** [comment]
P.S. after running `docker run my_gadgetron_image`, I run `gadgetron` in another terminal and get the error: `gadgetron: command not found`. How can I access the gadgetron executables from docker?

**Comment by KrisThielemans** [comment]
https://github.com/gadgetron/gadgetron/wiki/Using-Docker might answer your questions?

**Comment by casperdcl** [comment]
@rijobro once you've done `docker run` to start the container, gadgetron will already be running. Your host code (containing a gadgetron client interface) will simply use gadgetron over port 9002 which is forwarded to the container.

**Comment by casperdcl** [comment]
incidentally you can leave out all the GPU/nvidia stuff from the wiki link

**Comment by rijobro** [comment]
So I managed to get it working on my machine. Two things:
1. I can't do the Gadgetron unit tests. Maybe we can assume that their out-of-the-box docker versions pass them anyway?
2. I have no idea how to port this into the `travis.yml` file.

For the latter, installing and running it would be fairly easy:
```
docker pull gadgetron/ubuntu_1604_cuda80
docker run --publish=9002:9002 --volume=/tmp/gadgetron_data:/tmp/gadgetron_data --rm -t gadgetron/ubuntu_1604_cuda80
```

But we would then need to alter this section (and I'm not sure how):
```
script:
 - ./INSTALL/bin/gadgetron >& gadgetron.log&
 # print for debugging
 - cat builds/SIRF/build/CMakeCache.txt
 - ctest -VV
 # print for debugging
 - cat builds/SIRF/build/Testing/Temporary/LastTest.log
 # may exceed 4MB travis log limit
 - cat gadgetron.log
```

**Comment by KrisThielemans** [comment]
> I can't do the Gadgetron unit tests. Maybe we can assume that their out-of-the-box docker versions pass them anyway?

yes.

Regarding travis, I haven't tried, but is the `docker run` command not equivalent to `./INSTALL/bin/gadgetron &`
I see no need for any other changes

**Comment by rijobro** [comment]
> Regarding travis, I haven't tried, but is the docker run command not equivalent to ./INSTALL/bin/gadgetron &

Yes I would have thought so, but I wasn't sure how to do an `if`/`else` statement in this part of the travis script. 

Also, would we be able to keep the `gadgetron.log&` part of the first line, too?

**Comment by rijobro** [comment]
current attempt: 
```
script:
 - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      docker run --publish=9002:9002 --volume=/tmp/gadgetron_data:/tmp/gadgetron_data --rm -t gadgetron/ubuntu_1604_cuda80 >& gadgetron.log&
    else
      ./INSTALL/bin/gadgetron >& gadgetron.log&
    fi
 # print for debugging
 - cat builds/SIRF/build/CMakeCache.txt
 - ctest -VV
 # print for debugging
 - cat builds/SIRF/build/Testing/Temporary/LastTest.log
 # may exceed 4MB travis log limit
 - cat gadgetron.log
```

Branch is here: https://github.com/CCPPETMR/SIRF/tree/Gadgetron_OSX

**Comment by KrisThielemans** [comment]
looks ok to me. Does it work on your machine?

I guess I'd use a variable to see if we are using docker-gadgetron or not (we can test this on ubuntu as well). Could use `EXTRA_BUILD_FLAGS` to see if we're building Gadgetron or not as a work-around, but might be better to do it the other way around (set `BUILD_Gadgetron=OFF` if using docker). but that's fine-tuning.

**Comment by rijobro** [comment]
The [travis docs for docker](https://docs.travis-ci.com/user/docker/) give the following example:
```
language: ruby

services:
  - docker

before_install:
- docker pull carlad/sinatra
- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
```

However, after copying that, this line: 
```
docker pull gadgetron/ubuntu_1604_cuda80
```
gives the error:
```
docker: command not found
```

I think that the difference between their example and mine is that I used mine as part of the bash script.

Any idea what to do? I tried using `brew install docker` instead, but that ran into an initial startup problem:
```
Creating CA: /Users/travis/.docker/machine/certs/ca.pem

Creating client certificate: /Users/travis/.docker/machine/certs/cert.pem

Running pre-create checks...

Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```

@casperdcl any ideas?

**Comment by casperdcl** [comment]
Hah...

https://docs.travis-ci.com/user/docker/

> We do not currently support use of Docker on macOS.

**Comment by KrisThielemans** [comment]
This was fixed upstream, see https://github.com/gadgetron/gadgetron/issues/719
