### ISSUE TITLE
prefer existing system version of dependencies?

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#20]
Currently `USE_SYSTEM_BOOST` et al. default to `OFF`. This gives perfect control over versions, but causes long build times and potentially frustrates many people.

Opinions?

Please add your reaction via the ["reaction button"](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) at the top.

**Comment by paskino** [comment]
Gadgetron now builds with system boost libraries. We should use one, I guess.

**Comment by KrisThielemans** [comment]
Discussed in the 14th Software Meeting. General feeling was that it's better to keep complete control by default, i.e. have specific versions of dependencies. As external libraries are unlikely to exactly match what version we'd specify, it's probably not worth checking existence of matching-external libraries first (but would still be good to add at later stage).

I've created a new issue to document this, see #23.
