### ISSUE TITLE
find blas problem

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#233]
we get
```
CMake Warning at SuperBuild/External_Gadgetron.cmake:68 (find_package):
  By not providing "Findblas.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "blas", but
  CMake did not find one.
```
I believe I commented about this before but didn't find it.

**Comment by paskino** [comment]
On Linux something like this could work
```cmake 

if (ENABLE_BLAS)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(openblas REQUIRED openblas>=0.3)
  set(BLAS_LIBRARIES ${openblas_LIBRARIES})
  set(BLAS_INCLUDEDIR ${openblas_INCLUDEDIR})
endif()
```

**Comment by paskino** [comment]
I think [this](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_Gadgetron.cmake#L68) line is wrong. It should be 

```

**Comment by rijobro** [comment]
If I remember correctly, Gadgetron is the only package in the Superbuild that requires BLAS. We do the `find_package` so that we can pass `CBLAS_INCLUDE_DIR` and `CBLAS_LIBRARY` in `External_Gadgetron.cmake`.

As far as I understand, it doesn't matter how we do it provided we give these two variables. However, we do want to avoid Apple's library if possible (because of this issue: https://github.com/gadgetron/gadgetron/issues/719).

**Comment by paskino** [comment]
`CBLAS` is not picked up anyway. Gadgetron's got a `FindCBLAS.cmake` module.
However, the warning reported 
```
CMake Warning at SuperBuild/External_Gadgetron.cmake:68 (find_package):
  By not providing "Findblas.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "blas", but
  CMake did not find one.
```

is due to the fact that we issue `find_package(blas)` rather than `find_package(BLAS)`

**Comment by paskino** [comment]
just for reference this is the CMake documentation for https://cmake.org/cmake/help/v3.13/module/FindBLAS.html

At any rate, the only thing that must be changed is [this](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_Gadgetron.cmake#L68) line
```cmake 
find_package(BLAS)
```
