### ISSUE TITLE
wrong variable name default_BUILD_STIR_EXECUTABLES ?

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#242]
https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_STIR.cmake#L62

```cmake
set(default_BUILD_STIR_EXECUTABLES OFF)
  RenameVariable(BUILD_STIR_EXECUTABLES STIR_BUILD_EXECUTABLES default_STIR_BUILD_EXECUTABLES)
```
seems that in `RenameVariable` we use `default_STIR_BUILD_EXECUTABLES` instead than `default_BUILD_STIR_EXECUTABLES `

**Comment by KrisThielemans** [comment]
good catch. could you please correct this?
