### ISSUE TITLE
ITK always rebuilds

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF-SuperBuild#244]
When you run `make`, it seems that ITK always (or a lot of the time, I can't fully remember) rebuilds. Any ideas why this would be the case?

If nothing's changed, it only takes a minute or two, but it's a wasted minute or two...

**Comment by paskino** [comment]
I'm not sure how you'd know if something has changed in ITK without running `make ITK`. 

However I noticed the same behaviour that ITK would rebuild taking a lot of time. 

ITK is a [dependency](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_STIR.cmake#L27) of STIR

**Comment by KrisThielemans** [comment]
I don't think it's rebuilding, it's checking. It might be updating locations in installed shared libraries etc, which is something we have zero control over. Unless anyone has any ideas, I propose to close this.

**Comment by rijobro** [comment]
Just to clarify, when I run `make` in the directory where I've changed nothing since the last successful build, and get the following output:
```
[rmharbr@login12 Build]$ make
[ 11%] Built target Boost
[ 22%] Built target HDF5
[ 23%] Performing update step for 'ITK'
[ 25%] Performing configure step for 'ITK'
loading initial cache file /home/rmharbr/Code/SIRF-SuperBuild/Build/builds/ITK/tmp/ITK-cache-.cmake
-- Setting build type to 'Release' as none was specified.
-- Enabled ITKAnisotropicSmoothing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKAntiAlias, requested by ITK_BUILD_DEFAULT_MODULES.
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rmharbr/Code/SIRF-SuperBuild/Build/builds/ITK/build
[ 26%] Performing build step for 'ITK'
[  0%] Built target ITKData
[  0%] Built target itkdouble-conversion
[  0%] Built target ITKDoubleConversion-all
[  0%] Built target ITKKWIML-all
...
[100%] Built target ITKWatersheds
[100%] Built target ITKWatersheds-all
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/rmharbr/Code/SIRF-SuperBuild/Install/lib/cmake/ITK-4.13/ITKConfig.cmake
-- Up-to-date: /home/rmharbr/Code/SIRF-SuperBuild/Install/lib/cmake/ITK-4.13/ITKConfigVersion.cmake
...
```

So you can see that ITK is running `cmake`, `make` and `make install` every time. 

> I don't think it's rebuilding, it's checking.

Is this what you mean by "checking"?

**Comment by KrisThielemans** [comment]
yes. It's unfortunate that it takes so long, but I cannot see what we can do about it. You could always install ITK externally...

**Comment by rijobro** [comment]
You can even install with the superbuild then switch to using external ITK and pointing to the version that the superbuild built for you. Shame though.
