### ISSUE TITLE
use CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#25]
at present, we hardwire the location of where the dependencies are installed. I believe that the difficulty is that we cannot set a default `CMAKE_INSTALL_PREFIX` although I just found
https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html

@bathomas was there any other reason we don't use do this?

**Comment by bathomas** [comment]
No other reason. Just a legacy from when I started developing the SuperBuild.
