### ISSUE TITLE
setup environment variables at the end of the SuperBuild

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#26]
Make the SuperBuild create a “env_ccppetmr.sh” (and .csh?), and later even a Windows version, all installed in the `${INSTALL}/bin` directory. Then we tell people to run the SuperBuild, and source the appropriate .sh/.csh, either from the command line or from their .bashrc (or whatever the appropriate file is for the shell they are using).

This should be easy enough using
https://cmake.org/cmake/help/v3.2/command/configure_file.html

we make a skeleton (per shell-type) (based on our current .sirfc) like this

  SIRF_PATH=@SIRF_SRC_PATH@
  LD_LIBRARY_PATH=@CCPPETMR_INSTALL@/lib:$LD_LIBRARY_PATH
  PYTHONPATH=@CCPPETMR_INSTALL@/python:$PYTHONPATH
  PATH=$PATH:@CCPPETMR_INSTALL@/bin
  export SIRF_PATH
  export LD_LIBRARY_PATH
  export PYTHONPATH

and make 2 CMake variables accordingly. Then we just add a configure_file in SuperBuild.cmake statement and that’s it (I think).

**Comment by KrisThielemans** [comment]
fixed at 27023162d8a6d26143307090917875ec6f0455e3
