### ISSUE TITLE
[Azure] CUDA environment variables not set before starting Jupyter service

### ISSUE THREAD

**Issue by bathomas** [CCPPETMR/SIRF-SuperBuild#260]
The Jupyter service on gpu-enabled Azure VM does not start with appropriate CUDA environment variables set. Could be related to `$PATH`, `$LD_LIBRARY_PATH` and/or `$CUDA_HOME`.

**Comment by rijobro** [comment]
@bathomas this needs to be sorted I'm afraid. any ideas?

**Comment by KrisThielemans** [comment]
@bathomas I guess this is fixed? Can you please close mentioning the relevant commit?

**Comment by bathomas** [comment]
Fixed by 72e0edd
