### ISSUE TITLE
Travis updates

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF-SuperBuild#268]
- use stages (https://docs.travis-ci.com/user/build-stages/)
    + use conditionals for deployment, maybe allow Mac builds to fail https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
- may help with #167
- change default `dist` to 16.04 Xenial (https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide/) or even 18.04 Bionic (https://docs.travis-ci.com/user/reference/bionic/) instead of Trusty 14.04 (but perhaps retain one trusty build)

**Comment by casperdcl** [comment]
@KrisThielemans can you think of any reason to avoid updating travis to 16.04 or 18.04?

**Comment by KrisThielemans** [comment]
not really. I think having 16.04 would still be good, but if it creates a lot of trouble with docker install or so, it's probably better to go straight to 18.04

**Comment by casperdcl** [comment]
can change default to 18.04 but also have a couple of explicit 16.04 and 14.04 builds. We only do 14.04 at the moment which is pretty old.

**Comment by KrisThielemans** [comment]
don't volunteer for too much work :-)
