### ISSUE TITLE
SIRF-SuperBuild Ubuntu 17.04 installation failed

### ISSUE THREAD

**Issue by Evan27** [CCPPETMR/SIRF-SuperBuild#27]
Hi all,
I tried to install the SIRF-SuperBuild on my Linux (Ubuntu 17.04) box following the instractions from the web page: https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-Ubuntu-16.04
I had to install some packages before but when I run the steps:
cmake .
make 
in section 3 I get en error message when the configuration of gadgetron is performed without any obvious reason.
This is what I get:

[ 90%] Completed 'Armadillo'
[ 90%] Built target Armadillo
Scanning dependencies of target Gadgetron
[ 92%] Creating directories for 'Gadgetron'
[ 93%] Performing download step (git clone) for 'Gadgetron'
Cloning into 'Gadgetron'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 94%] No patch step for 'Gadgetron'
[ 95%] Performing update step for 'Gadgetron'
Current branch master is up to date.
[ 96%] Performing configure step for 'Gadgetron'
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for packages in : /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/
-- Found Git: /usr/bin/git (found version "2.11.0") 
64bit system is found
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
OpenMP multithreading enabled
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   system
--   thread
--   program_options
--   filesystem
--   timer
--   chrono
--   date_time
--   atomic
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE include: /usr/include
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "5.5") 
Compiling with -gencode arch=compute_30,code=sm_30;-gencode arch=compute_35,code=sm_35;-gencode arch=compute_50,code=sm_50;-gencode arch=compute_52,code=sm_52
-- Found GTest: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libgtest.a  
-- Found Armadillo: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libarmadillo.so (found suitable version "7.800.2", minimum required is "4.600") 
Armadillo found. Note that ARMADILLO_BLAS_LONG_LONG _must_ be defined in /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/include/armadillo_bits/config.hpp to link against the MKL ILP64 interface.
-- Found HDF5: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5_cpp-shared.so;/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5-shared.so (found suitable version "1.10.0.1", minimum required is "1.8") found components:  C CXX HL 
FFTW3 UNIX libraries: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3f.a/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3.a
-- Found FFTW3: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3f.a  
MKL is NOT found ... 
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
LAPACK Found
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.13", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.13") 
-- Found NumPy: version "1.12.1" /usr/lib/python2.7/dist-packages/numpy/core/include
-- Could NOT find Matlab (missing:  MATLAB_ROOT MATLAB_INCLUDE_DIR MATLAB_LIBRARIES) 
Searching for OpenGL, GLEW, GLUT, and Qt. These libraries are only used in a single standalone application and are thus non-essential.
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
GLEW NOT FOUND
-- Could NOT find GLUT (missing:  GLUT_glut_LIBRARY GLUT_INCLUDE_DIR) 
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
-- Found unsuitable Qt version "" from NOTFOUND
PLplot is found at /usr/include/plplot
-- Found HDF5: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5_cpp-shared.so;/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5-shared.so (found version "1.10.0.1") found components:  HL 
Compiling cpu based optical flow registration toolbox.
Compiling gpu based optical flow registration toolbox.
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   system
--   thread
--   regex
--   chrono
--   atomic
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE include: /usr/include
-- Boost version: 1.63.0
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   python
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.13") 
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   python
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Found HDF5: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5_cpp-shared.so;/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5-shared.so (found suitable version "1.10.0.1", minimum required is "1.8") found components:  C 
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   program_options
--   thread
--   system
--   chrono
--   date_time
--   atomic
Matlab not found. Matlab wrapper for registration toolbox will not be compiled.
MATLAB NOT FOUND: matlab wrapper for gtplus toolbox will not be compiled.
-- Found HDF5: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5_cpp-shared.so;/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5-shared.so (found version "1.10.0.1") found components:  HL 
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE include: /usr/include
FFTW3 UNIX libraries: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3f.a/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3.a/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3f.a/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libfftw3.a
ZFP NOT Found
-- Found HDF5: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5_cpp-shared.so;/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libhdf5-shared.so (found suitable version "1.10.0.1", minimum required is "1.8") found components:  C 
Cuda found, compiling gpu accelerated gadgets
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   python
--   system
--   thread
--   chrono
--   date_time
--   atomic
PYTHON_INCLUDE_DIRS: /usr/include/python2.7
PYTHON_LIBRARIES: /usr/lib/x86_64-linux-gnu/libpython2.7.so
NUMPY_INCLUDE_DIRS: /usr/lib/python2.7/dist-packages/numpy/core/include
Compiling Python Gadgets
-- /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/include/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libboost_python.so/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libboost_system.so/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libboost_thread.so/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libboost_chrono.so/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libboost_date_time.so/home/evan/Documents/devel/SIRF-SuperBuild/INSTALL/lib/libboost_atomic.so
-- Could NOT find DCMTK (missing:  DCMTK_config_INCLUDE_DIR DCMTK_ofstd_INCLUDE_DIR DCMTK_ofstd_LIBRARY DCMTK_oflog_INCLUDE_DIR DCMTK_oflog_LIBRARY DCMTK_dcmdata_INCLUDE_DIR DCMTK_dcmdata_LIBRARY DCMTK_dcmimgle_INCLUDE_DIR DCMTK_dcmimgle_LIBRARY) 
DCMTK NOT found, not compiling DICOM gadget
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") 
CMake Error at chroot/CMakeLists.txt:41 (get_filename_component):
  get_filename_component unknown component
  /usr/lib/x86_64-linux-gnu/libcublas_device.a

CPACK_PACKAGING_INSTALL_PREFIX: /home/evan/Documents/devel/SIRF-SuperBuild/INSTALL
-- Found CPack generators: DEB
-- Configuring incomplete, errors occurred!
See also "/home/evan/Documents/devel/SIRF-SuperBuild/Gadgetron-prefix/src/Gadgetron-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/Gadgetron.dir/build.make:111: recipe for target 'Gadgetron-prefix/src/Gadgetron-stamp/Gadgetron-configure' failed
make[2]: *** [Gadgetron-prefix/src/Gadgetron-stamp/Gadgetron-configure] Error 1
CMakeFiles/Makefile2:338: recipe for target 'CMakeFiles/Gadgetron.dir/all' failed
make[1]: *** [CMakeFiles/Gadgetron.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any suggestions ?
Regards
Evan

**Comment by KrisThielemans** [comment]
This is an upstream problem. New issue created. https://github.com/gadgetron/gadgetron/issues/524

**Comment by KrisThielemans** [comment]
I've attempted to fix this. Can you please try to build with
```
cmake -DGadgetron_TAG=chroot_fixes
```
(in addition to any other settings you need).

**Comment by KrisThielemans** [comment]
fixed with updates accepted by Gadgetron
