### ISSUE TITLE
cmake syntax `if(!var)`

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#290]
Does `!` actually work in CMake?
https://github.com/CCPPETMR/SIRF-SuperBuild/blob/baab2ac58b577a83e894e4e43b65d1d7985554ce/SuperBuild/External_STIR.cmake#L109
I think it has to be
`if (NOT USE_ITK)`
usage of `!` is not documented. https://cmake.org/cmake/help/v3.16/command/if.html

**Comment by rijobro** [comment]
Apologies looks like that one was me. Simple test shows that `!` doesn't work.

```
SET(A OFF)
if (!A)
	message(FATAL_ERROR "A is false")
else()
	message(FATAL_ERROR "A is true")
endif()
```
Always returns true regardless of value of `A`. 

I'll fix this now.
