### ISSUE TITLE
Travis green but all OSX red

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF-SuperBuild#292]
All OSX jobs are red, yet the overall Travis status is green. Check the current master branch, for example: https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/builds/609322527.

I suppose it's related to this small message at the bottom of the screen:

```
Your build matrix was set to allow the failure of multiple jobs so we continued this build to the next stage.
```

The problem is that we're wasting 45 mins per build, all of which we already know are going to fail.

@casperdcl looking at the git blame I think you might have been playing with the `.travis.yaml` recently?

Globally, it also seems that we have many more test matrices than before, is that necessary?

**Comment by casperdcl** [comment]
On Tue, 12 Nov 2019, 4:06 pm

> Latest job failure
>
> ls: /usr/local/Cellar/python/.*/Frameworks/Python.framework/Versions/.*: No such file or directory
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
Something wrong with finding Python executable for OSX
PY_EXE = /bin/python
>
> See https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/610907054
 
> Thanks to Casper, it no longer causes out Travis status to be red (thanks  Casper). Nevertheless, it seems that brew has moved things around yet again, and that’ll hurt someone somewhere… not urgent to fix, but we should have some pointers on our wiki (maybe we do already).

-- @KrisThielemans

I was wondering how long it would take for someone to complain about the extra time :D

As @KrisThielemans noted I deliberately allow osx failures

**Comment by rijobro** [comment]
Is it a mix up between python2 and python3?:
https://github.com/CCPPETMR/SIRF-SuperBuild/blob/baab2ac58b577a83e894e4e43b65d1d7985554ce/.travis.yml#L350
We're in the `if` clause of `python3`, but we're doing `brew update python`.

**Comment by rijobro** [comment]
Sorry, just realised `brew upgrade python` will do `python3`...

**Comment by rijobro** [comment]
Anyway, I don't know why but it looks like `PYMVER` is empty, such that `/$PYMVER.*` gives just `/.*`.

**Comment by casperdcl** [comment]
maybe `$PYMVER.*` needs to be `${PYMVER}.*`

**Comment by rijobro** [comment]
I tried locally and there was no need for brackets. Anyway, I don't see that error in current Travis logs. Looks like they're failing because ([link](https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/609322540)):
```
[ 80%] Linking CXX shared module _pygadgetron.so

Undefined symbols for architecture x86_64:

  "boost::detail::thread_data_base::~thread_data_base()", referenced from:

      boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, sirf::GadgetronClientConnector>, boost::_bi::list1<boost::_bi::value<sirf::GadgetronClientConnector*> > > >::~thread_data() in libcgadgetron.a(gadgetron_client.cpp.o)

      boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, sirf::GadgetronClientConnector>, boost::_bi::list1<boost::_bi::value<sirf::GadgetronClientConnector*> > > >::~thread_data() in libcgadgetron.a(gadgetron_client.cpp.o)

  "boost::thread::join_noexcept()", referenced from:

      boost::thread::join() in libcgadgetron.a(cgadgetron.cpp.o)

      boost::thread::join() in libcgadgetron.a(gadgetron_x.cpp.o)
...
```

i.e., `boost::thread` requires `boost::detail`. But we currently only find the following components:

https://github.com/CCPPETMR/SIRF/blob/4391045e0032226e860630c79d5950a9b112d5cf/CMakeLists.txt#L76

Attempted fix: https://github.com/CCPPETMR/SIRF/pull/470.

**Comment by casperdcl** [comment]
@rijobro surely debugging to fix this should be done in a branch on this repo (SuperBuild) rather than SIRF? Any reason you picked SIRF?

**Comment by rijobro** [comment]
This could've been debugged on the SuperBuild or SIRF, the problem should be fixed on SIRF via https://github.com/CCPPETMR/SIRF/pull/470. I'll do the same here and hopefully that should all be solved. 

When it is solved, I'll remove the following:
```
allow_failures:
 - os: osx
```
