### ISSUE TITLE
Write FindSTIR and FindISMRMRD

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#30]
SIRF build actually fails because it does not find STIR and ISMRMRD and therefore it builds only the utils.

**Comment by KrisThielemans** [comment]
hi. This has to be new behaviour in your branch. It all worked before. Also, writing Find packages isn't necessary as both of this have "config.cmake" files. If CMake doesn't find it, it means setting STIR_DIR to where the STIRConfig.cmake file is located (and same for ISMRMRD).

**Comment by KrisThielemans** [comment]
This was because of a mistake in the branch, so closing this issue.
