### ISSUE TITLE
ITK source code directory path length is too long

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF-SuperBuild#302]
Could not build ITK on my Windows 10 desktop, got the error
```
6>  Performing configure step for 'ITK'
6>  loading initial cache file C:/Users/wps46139/Documents/GitHub/try/build/SIRF-SuperBuild/builds/ITK/tmp/ITK-cache-Release.cmake
6>  CMake Error at CMakeLists.txt:57 (message):
6>    ITK source code directory path length is too long (72 > 50). Please move the
6>    ITK source code directory to a directory with a shorter path.
```

**Comment by rijobro** [comment]
Looking at the [ITK source code CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITK/blob/83d92e8c8da27243ed9f6ec3d0e7324c2af80e53/CMakeLists.txt#L105): 
```
if( CMAKE_HOST_WIN32 AND NOT ITK_SKIP_PATH_LENGTH_CHECKS )
```
So if you set `ITK_SKIP_PATH_LENGTH_CHECKS` to `ON`, you should be fine (or you won't see this error at least). Something along the lines of:
```
cd builds/ITK/build && cmake . -DITK_SKIP_PATH_LENGTH_CHECKS=ON
```

**Comment by evgueni-ovtchinnikov** [comment]
I added `ITK_SKIP_PATH_LENGTH_CHECKS` in CMake GUI and checked it - same error message.

Adding
```
message("ITK_SKIP_PATH_LENGTH_CHECKS: ${ITK_SKIP_PATH_LENGTH_CHECKS}")
```
to ITK CMakeLists.txt produced
```
5>  ITK_SKIP_PATH_LENGTH_CHECKS: 
```

**Comment by rijobro** [comment]
> I added ITK_SKIP_PATH_LENGTH_CHECKS in CMake GUI

It looks like you didn't (or didn't add it in the right place).

Where were you running CMake GUI? Which folder is displayed next to "Where to build the binaries:" at the top of the GUI?

**Comment by evgueni-ovtchinnikov** [comment]
I tried to build ITK as part of SuperBuild so the destination folder was
```
.../build/SIRF-SuperBuild
```
I am now building ITK on its own in
```
.../build/SIRF-SuperBuild/builds/ITK
```
(looks building ok so far) but is this really how we want our users to build it?

**Comment by rijobro** [comment]
Each of the dependencies has many CMake options. We don't wrap all those options, just the ones we deem important. This means that if you're coming across a problem for the first time (as you are now), the relevant parameters may not be set through the superbuild. You can see a list of the CMake flags that we pass from the superbuild to ITK in `Superbuild/External_ITK.cmake`:

https://github.com/CCPPETMR/SIRF-SuperBuild/blob/e1c7e3507ec6c8846db248087fea55e21e231365/SuperBuild/External_ITK.cmake#L65-L80

If you want to be able to set a new variable in the superbuild, you need to ensure it's also getting passed to the relevant dependency.

To do that: 
Create an option in `Superbuild/External_ITK.cmake`:
```
option(ITK_SKIP_PATH_LENGTH_CHECKS "Tell ITK to not check lengths of paths" ON)
```
Pass that option to ITK (again in `Superbuild/External_ITK.cmake`):
```
CMAKE_ARGS
      -DCMAKE_PREFIX_PATH=${SUPERBUILD_INSTALL_DIR}
      ...
      -DITK_SKIP_PATH_LENGTH_CHECKS:BOOL=${ITK_SKIP_PATH_LENGTH_CHECKS}
	  INSTALL_DIR ${${proj}_Install_Dir}
    DEPENDS ${${proj}_DEPENDENCIES}
  )
```
