### ISSUE TITLE
CIL_VERSION undefined for DEVEL_BUILD

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF-SuperBuild#304]
https://github.com/CCPPETMR/SIRF-SuperBuild/blob/5136e69a153db16939ef67081ef85c2c30cf493e/version_config.cmake#L213

`CIL_VERSION` is undefined for `DEVEL_BUILD=ON`, which means that CIL packages can't be built (CCPi-Regularisation requires it as an environmental variable, for example).

**Comment by KrisThielemans** [comment]
In addition, CCPi tags are by default set to `origin/master`, bound to break stuff. @paskino, please change to a tag. Then undo #310
