### ISSUE TITLE
Installation typos/bugs in README.md

### ISSUE THREAD

**Issue by AnderBiguri** [CCPPETMR/SIRF-SuperBuild#318]
This is what I found so far:

1. In Line 61-62 (https://github.com/CCPPETMR/SIRF-SuperBuild/edit/master/README.md#L61). User is at `/opt/cmake` so commands should not point at `/tmp/...` but `/opt/cmake/....`

2. In Line 68 (https://github.com/CCPPETMR/SIRF-SuperBuild/edit/master/README.md#L68). We have not created such folder, so it should read `export PATH=/opt/cmake/bin:$PATH`

**Comment by rijobro** [comment]
It seems that `use_SYSTEM_ACE` defaults to `ON`, and yet even though Ander didn't have ACE installed, no error was thrown. Strange given that the following is present in `External_ACE.cmake`:
```
find_package(${proj} ${${externalProjName}_REQUIRED_VERSION} REQUIRED)
```

**Comment by KrisThielemans** [comment]
There's indeed a number of errors in the README.md. The duplication of the PATH lines (with the 2nd version incorrect) is I think a left-over from when we were using the CMake install script. I can't see the `tar` asking questions... @AnderBiguri please create a PR.

While at it, I suggest to change the instruction to something like
````
ver=...
location=/opt # set to desired location where CMake will be isntalled
```
and then use `${location}` as opposed to `/opt`. Then please add a line that CMake doesn't have to be installed in a system location, and `sudo`  permissions are then not required.

**Comment by KrisThielemans** [comment]
I've moved the ACE  error to #319. Please comment there on that issue.

By the way@, @AnderBiguri please don't use links to the an Edit version of a file.

**Comment by AnderBiguri** [comment]
Sure, will do.
Is there any reason why just doing

sudo apt-get install cmake


Is not suggested here? Or can we add that option too?

**Comment by KrisThielemans** [comment]
there's a line above about using your system cmake I believe. We do need 3.10 or more recent, which isn't always installed by `apt` and similar (it isn't in Ubuntu 16.04).  I don't think we should be listing all possible package managers here though. Feel free to try to update to something concise and helpful!

**Comment by AnderBiguri** [comment]
Sure, I understand. Simply just asking, I am not very fluent on Linux and
it's flavours, more of a curious question than a suggestion. Will make a PR
with proposed changes.

**Comment by rijobro** [comment]
I would vote removing cmake installation help altogether in favour of pointing them to CMake's homepage. One less thing to keep track of...

**Comment by KrisThielemans** [comment]
certainly point to their install-page (if we don't do that yet). I'd like to keep the explicit instructions for Ubuntu as it reduces variability a bit.  Maybe best to just point to https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/INSTALL_CMake.sh for an explicit example.
