### ISSUE TITLE
FFTW has removed version 3.3.5 from http site

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#320]
Can't download and find version 3.3.5 now and build will fail.

Should increase the version in `version_config.cmake`

**Comment by paskino** [comment]
Actually, it's better to change the `FFTW_URL` from `http://www.fftw.org/fftw-3.3.5.tar.gz` to `ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5.tar.gz`

**Comment by KrisThielemans** [comment]
file is back on `http`, so closing.
