### ISSUE TITLE
clean-up conditional git checkout code

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#336]
It would be shorter/cleaner to set the `git` arguments to a macro, like I did with the directory arguments #326. I suggest to create a variable `${proj}_EP_ARGS_GIT` in `SetGitTagAndRepo`  to replace the usage of
```cmake
GIT_REPOSITORY "${${proj}_URL_MODIFIED}"
GIT_TAG "${${proj}_TAG_MODIFIED}"
```
(or equivalent without `_MODIFIED`) in the `External_*` cmake files.

Seems that we could then replace https://github.com/CCPPETMR/SIRF-SuperBuild/blob/602922caf315b073b814aa1c3f8806f2f50e4db9/CMake/SetGitTagAndRepo.cmake#L39-L48 with
```cmake
         # set a variable to use in the ExternalProject_Add call that sets all git-related variables
	if (EXISTS "${${proj}_SOURCE_DIR}" AND DISABLE_GIT_CHECKOUT_${proj})
                set(${proj}_EP_ARGS_GIT)
		message(STATUS "Not going to perform git checkout for ${proj}...")
	else()
		message(STATUS "Will perform git checkout for ${proj}...")
                set(${proj}_EP_ARGS_GIT
                    GIT_REPOSITORY ${${proj}_URL}
                    GIT_TAG ${${proj}_TAG}
                 )
             endif()
	endif()
```

**Comment by KrisThielemans** [comment]
@AnderBiguri want to have a go?

**Comment by AnderBiguri** [comment]
@KrisThielemans sure.

**Comment by rijobro** [comment]
Our current method of setting URL and tag to `""` means that no new git checkouts are done. This is fine when the source is already in place, but causes an error when building the first time.

i.e., the following will fail:
```
mkdir new_folder
cd new_folder
cmake ../SB_source -DDISABLE_GIT_CHECKOUT_SIRF:BOOL=ON 
```

Since we're planning to clean up the git checkout method, perhaps it would be a good moment to sort this out. Any ideas?
