### ISSUE TITLE
Add option to set Git tag and repository URL to all (or some) External_*.cmake

### ISSUE THREAD

**Issue by AnderBiguri** [CCPPETMR/SIRF-SuperBuild#341]
Currently  only `External_Gadgetron.cmake`, `External_NIFTYREG.cmake` (in PR https://github.com/CCPPETMR/SIRF-SuperBuild/pull/335), `External_SIRF.cmake` and `External_STIR.cmake` have this option. 

Should we add `SetGitTagAndRepo("${proj}")` to the rest? Not sure if it makes sense for Armadillo or `boost`, but perhaps `NIFTYPET` or `SPM` or `CCPi_*` could use this variable?

**Comment by KrisThielemans** [comment]
Let's do this on a need basis. It would in any case make more sense to use one more macro that call the 3 other macros etc. Even less lines to write.
