### ISSUE TITLE
Generate functionality to pass all variables to  External CMakes

### ISSUE THREAD

**Issue by AnderBiguri** [CCPPETMR/SIRF-SuperBuild#342]
### Preamble 

I am having serious problems compiling and running the SuperBuild. I did manage to have something working at some point by modifying and unknown amount of variables in the `cmake-gui` of `./build` and `./build/builds/XXXXXX/build`. At some point I managed to screw over it again and could not continue. @rijobro Suggested a better alternative to keep track of changes. To Have a bash script where I go passing variables as I manage to compile parts of it, something like:

```
mkdir -p build
cd build

cmake ../SIRF-SuperBuild \
-DBUILD_Gadgetron:BOOL=OFF \
 ...
```

This is great because I can go changing variables and turning on slowly the flags of libraries to build.

### Problem

This can not access flags that are not set by the SuperBuild Cmake. If someone wanted to change e.g. `BUILD_MATLAB_WRAPPER` inside `CCPi_Regularisation_Tookit/build`, the only way to do it is to go to that particular CMake, and change it. Unfortunately, this means to again, lose track of teh changes. Passing all variables to the main CMake sounds like a tedious and unmaintainable task

### Proposed Solution
(by @rijobro )
Make a macro `SetExtraArgs.cmake` that would parse input flags like: `-DCCPi_Regularisation-Toolkit_SET_VAR_BUILD_MATLAB_WRAPPER:BOOL=ON`, then parse it (regexp or otherwise, using `${proj}`) and extract the part after `_SET_VAR_`. Make a list and then pass it in the `CMAKE_ARGS` section of `External_CCPi-Regularisation-Toolkit.cmake` 

### Problems with this solution

Mostly that it exposes all variables (but encapsulation is not necessarily what we want here right?) and that we need to modify all the `External_*` files. 

I am happy to take upon this issue and happy to hear other options/solutions. 
Or is this something that its "just me" and we do not want it in the SuperBuild?

**Comment by KrisThielemans** [comment]
proposed solution:
```cmake
set(${proj}_EXTRA_CMAKE_ARGS "" CACHE STRING "Optional extra CMake arguments to be appended to the flags set by the SuperBuild")
mark_as_advanced(${proj}_EXTRA_CMAKE_ARGS)

ExternalProject_Add(
....

  CMAKE_ARGS
 ...
   {proj}_EXTRA_CMAKE_ARGS
)
```
would then make sense to put the first 2 lines in a separate file defining yet another macro, such that they don't need to be repeated.

I guess we want it to allow overriding SuperBuild args. I'm not sure about prepending vs appending then. easy to try (or read the CMake doc...)

Of course, we could have the same for non-cmake projects (`..._EXTRA_CONFIGURE_FLAGS` or whatever) but let's only do this when we need it!

**Comment by AnderBiguri** [comment]
@KrisThielemans The "issue" with this way is that the `CACHE` will enforce past set variables. So once you have done `-DSTIR_EXTRA_CMAKE_ARGS:STRING=-Dsomething:BOOL=ON`, if you remove it from your CMAKE call, `-Dsomething:BOOL=ON` will be set forever. This includes also if its a typoed variable. It is not necessarily wrong, but it hides from the user that if a flag is removed from the CMAKE call, it is still set. 

I have tried other types of `set` calls, such as `set(${proj}_EXTRA_CMAKE_ARGS "" CACHE INTERNAL STRING "")` which I though would remove this issue, but with no positive results.

I read that we can use `unset` to remove `CACHE` variables.

I guess my question is: What is the approach we should take? Should I `unset` and then `set` the `EXTRA_CNAKE_ARGS` or should we leave as you proposed, perhaps with some `message` printing the cached values?
