### ISSUE TITLE
Do not use master for DEVEL build of CCPi code

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#347]
@paskino @epapoutsellis I feel that our Travis or DEVEL builds shouldn't be failing because CCPi code is failing (as currently in #331). Presumably CCPi has its own testing suite. I therefore suggest to modify [version_config.cmake](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/d5a2e679579b149b910e4cbff2ad908f94771d48/version_config.cmake#L181-L187) to known-working commits (or tags) for the `DEVEL` build as well.

Obviously, that hash/tag should be such that the tests for `master` of SIRF work.

This is the same as what we do for Gadgetron etc. We had continuing Gadgetron build problems until we fixed the version.

**Comment by rijobro** [comment]
Closing this as now only CCPi-FrameworkPlugins points to master and that's unlikely to cause a Travis problem as it's python only (just a folder copy by CMake I believe). All other CCPi tags have been tested and Travis is happy with them.
