### ISSUE TITLE
Travis builds with system SWIG, HDF5 and FFTW3

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#37]
I noticed that in the [.travis.yml](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/.travis.yml#L22) we use 
`EXTRA_BUILD_FLAGS="-DUSE_SYSTEM_SWIG=ON -DUSE_SYSTEM_HDF5=ON -DUSE_SYSTEM_FFTW3=ON`

Is that correct? Should not we use the SWIG, HDF5 and FFTW3 that are built as part of the SuperBuild? Or these settings do not do anything?

**Comment by casperdcl** [comment]
`ccache`?

also note we can use https://docs.travis-ci.com/user/docker/ so perhaps cache docker layers.

and [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out)
