### ISSUE TITLE
changing an External*.cmake doesn't cause rebuild

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#4]
I ran "cmake .; make", then updated External_Boost_configureboost.cmake (by switching branch), which added some extra boost libraries, but those libraries never got build. This might be a CMake problem, not ours.

CMake version 3.7.0.

**Comment by casperdcl** [comment]
I think you need to rerun cmake configure whenever you make those sort of changes.

**Comment by KrisThielemans** [comment]
this must have been a fluke or CMake bug. The `External*` files are listed as dependencies now.
