### ISSUE TITLE
env_ccppetmr.*sh sets wrong SIRF_PATH in out-of-source build

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#42]
Currently using
```
set(SIRF_SRC_PATH ${CMAKE_CURRENT_LIST_DIR}/SIRF)
```
but this is incorrect if we build somewhere else from where we cloned. Presumably
```
set(SIRF_SRC_PATH ${CMAKE_CURRENT_BINARY_DIR}/SIRF)
```

**Comment by paskino** [comment]
Yes! I found that out yesterday. I've replaced it with `$SOURCE_DOWNLOAD_CACHE` which is a copy of `$CMAKE_CURRENT_BINARY_DIR`

**Comment by paskino** [comment]
Closed with https://github.com/CCPPETMR/SIRF-SuperBuild/commit/4cf709b8f83d82fbb633871350db4471cbbeca6f
