### ISSUE TITLE
merge HDF5_DIR_fixes branch

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#44]
there are some commits here that were actually in the release.

**Comment by KrisThielemans** [comment]
devel is now merged. Other things on this branch are for Windows and need to be reviewed, so moving this to v1.0.

**Comment by casperdcl** [comment]
`USE_SYSTEM_HDF5=OFF` now fails https://travis-ci.org/CCPPETMR/SIRF/jobs/317346200

**Comment by KrisThielemans** [comment]
download failed. @bathomas has had similar problems recently. seems their website isn't very reliable (somewhat amazing for the HDF5 group). I guess we could grab it from somewhere else, even make it part of our release.

**Comment by casperdcl** [comment]
just restarted, seems to be downloading again now

**Comment by KrisThielemans** [comment]
caution, this branch is out-of-date. don't merge! I'll delete it, but need to check which HDF5 version was used.

**Comment by KrisThielemans** [comment]
relevant bits are in HDF-fixes branch and will be merged, so closing this.
