### ISSUE TITLE
add MATLABPATH to env_ccppetmr.*sh

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#46]
It'll make people's life easier if SIRF gets added to the Matlab path automatically. I suggest that we set `MATLABPATH`, see https://uk.mathworks.com/help/matlab/matlab_env/add-folders-to-matlab-search-path-at-startup.html. I don't see any downsides.

**Comment by paskino** [comment]
Closed with https://github.com/CCPPETMR/SIRF-SuperBuild/commit/e167bc77feb039acdac93f6fef4658265b225900
