### ISSUE TITLE
PYTHON_DEST is not set to the install directory

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#52]
[`PYTHON_DEST`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_SIRF.cmake#L45) does not point to the same directory as [`PYTHONPATH`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/env_ccppetmr.sh.in#L17)

**Comment by paskino** [comment]
This issue is a CMake cache issue.

**Comment by evgueni-ovtchinnikov** [comment]
I just have downloaded and imported again SIRF_0.9.2_Ubuntu16.04_VM, run update_VM.sh and ccmake after configuring showed PYTHON_DEST to be /home/surfuser/devel/SIRF-SuperBuild/INSTALL/python, whereas PYTHONPATH is /home/surfuser/devel/install/python.

So, the issue is apparently still there ☹.

**Comment by paskino** [comment]
Is this still relevant?

**Comment by evgueni-ovtchinnikov** [comment]
For the current VM, it is. But you were going to make a new one, were you not?

**Comment by KrisThielemans** [comment]
should all be fixed now, especially with #66.
