### ISSUE TITLE
Linux link failure when using python 3.5

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#57]
current link errors are like
```
[ 27%] Linking CXX executable gadgetron_test_python

/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libboost_python.so: undefined reference to `PyString_InternFromString'
```
This is with `USE_SYSTEM_BOOST=On` but using a virtualenv for Python 3.5 (Python 2.7 works). It seems Gadgetron needs to link with `libboost_python-py35.so`.

**Comment by casperdcl** [comment]
possibly a gadgetron issue? Master's still failing: https://travis-ci.org/CCPPETMR/SIRF-SuperBuild

I've also just added https://travis-ci.org/CCPPETMR/SIRF (PR: https://github.com/CCPPETMR/SIRF/pull/69) which tried to use `SuperBuild:master` and `SuperBuild:v0.9.2` to build `SIRF:coverage`

**Comment by KrisThielemans** [comment]
This gadgetron linking error will disappear onc we update its tag to later than the merge with https://github.com/gadgetron/gadgetron/pull/552, i.e. at least https://github.com/gadgetron/gadgetron/commit/21d584927ee35c8d351a0bd72284b472da555d57. However, I see a few gadgetron bug fixes later which might be useful for us, e.g. https://github.com/gadgetron/gadgetron/commit/6a0482e0cbcf5bfea3a55fdd110b485ad0a9bdf0 and https://github.com/gadgetron/gadgetron/commit/e7eb430673eb3272e8a821b51750c0a2a96dafed.
@evgueni-ovtchinnikov, can you update `version_config.cmake` to use the latter and run the tests?

**Comment by evgueni-ovtchinnikov** [comment]
successfully tested with the gadgetron commit e23da883867819947fe16ca6ab9bf467079b7369 - is it recent enough?

**Comment by KrisThielemans** [comment]
as I said above  (but rather unclearly!), please test with https://github.com/gadgetron/gadgetron/commit/e7eb430673eb3272e8a821b51750c0a2a96dafed

**Comment by casperdcl** [comment]
still failing: https://travis-ci.org/CCPPETMR/SIRF/builds/311558374

**Comment by KrisThielemans** [comment]
All PET errors seem to be of the form
```
Command: "/home/travis/virtualenv/python3.5.3/bin/python" "test1.py"
Directory: /home/travis/build/CCPPETMR/SIRF-SuperBuild/SIRF/src/xSTIR/pSTIR/tests/
"PET_TEST1" start time: Dec 04 22:57 UTC
Output:
----------------------------------------------------------
/home/travis/virtualenv/python3.5.3/bin/python: can't open file 'test1.py': [Errno 2] No such file or directory
```
That's of course because you switched to `nosetest`  but didn't adapt the ctest lines yet (the `nosetests` at the end do work ok.

There's one MR test that fails
```
"MR_TEST3" start time: Dec 04 22:57 UTC
Output:
----------------------------------------------------------
Exception ignored in: <bound method pTest.__del__ of <pUtilities.pTest object at 0x7fb2982364a8>>
Traceback (most recent call last):
  File "/home/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/pUtilities.py", line 216, in __del__
    raise ValueError("%d failures" % self.failed)
ValueError: 13 failures
ismrmrd-python-tools not installed
```
The exception worries me (we've had a discussion on something that cannot be caught before), can't remember where). @evgueni-ovtchinnikov does this test need `ismrmrd-python-tools`?

**Comment by evgueni-ovtchinnikov** [comment]
successfully tested with the gadgetron commit e23da883867819947fe16ca6ab9bf467079b7369 - is it recent enough?

**Comment by evgueni-ovtchinnikov** [comment]
"MR_TEST3" start time: Dec 04 22:57 UTC 
    Output:
    ----------------------------------------------------------
    Exception ignored in: <bound method pTest.__del__ of <pUtilities.pTest object at 0x7fb2982364a8>>
    Traceback (most recent call last):
      File "/home/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/python/pUtilities.py", line 216, in __del__
        raise ValueError("%d failures" % self.failed)
    ValueError: 13 failures
    ismrmrd-python-tools not installed

This is very puzzling.
For one thing, my line 216 in pUtilities.py is
                expected = self.data[self.ntest]
Furthermore, I could not find the line
        raise ValueError("%d failures" % self.failed)
in any of my files.

As for 
    ismrmrd-python-tools not installed
it is not an error but just warning - I will move it to its proper place so that it does not pop up every time pGadgetron is imported.

**Comment by evgueni-ovtchinnikov** [comment]
as I said above (but rather unclearly!), please test with gadgetron/gadgetron@e7eb430

Done, all well. Should I push?

**Comment by KrisThielemans** [comment]
yes please

**Comment by evgueni-ovtchinnikov** [comment]
As for
    ismrmrd-python-tools not installed
    it is not an error but just warning - I will move it to its proper place so that it does not pop up every time pGadgetron is imported.

Some clarification is needed: this is _normally_ just a warning, which, however, becomes a fatal error if the user's script tries to compute coil sensitivity maps using Inati method - so, I now moved (on devel) the import of ismrmrd-python-tools to CSM calculation method.

**Comment by evgueni-ovtchinnikov** [comment]
as I said above (but rather unclearly!), please test with gadgetron/gadgetron@e7eb430

        Done, all well. Should I push?

    yes please

Done

**Comment by evgueni-ovtchinnikov** [comment]
As for
        ismrmrd-python-tools not installed
        it is not an error but just warning - I will move it to its proper place so that it does not pop up every time pGadgetron is imported.

    Some clarification is needed: this is normally just a warning, which, however, becomes a fatal error if the user's script tries to compute coil sensitivity maps using Inati method - so, I now moved (on devel) the import of ismrmrd-python-tools to CSM calculation method.

Forgot to write: none of the tests uses Inati method for CSM calculations (one demo does, though).

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov can this be closed?
