### ISSUE TITLE
what to do with BUILD_TESTING?

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#6]
Several sub-projects have BUILD_TESTING.
We could provide several options (no testing, test only SIRF, test everything). In some sense however the "test only SIRF" is flawed as the dependencies need to work correctly. But running all the tests is going to take a looong time.

I guess we could have a CMake option for every project dependency (could maybe be done semi-automatically: add an option BUILD_TESTING_${proj}, which then sets its BUILD_TESTING).

This would allow the developer to choose what tests to run.

**Comment by casperdcl** [comment]
:+1:
