### ISSUE TITLE
adding PYTHON_EXECUTABLE to env_ccppetmr.*?

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#60]
With Python there's considerable scope for running the wrong version, i.e. not the one with which SIRF was compiled. We could reduce the chances for this happening by add a variable to our environment variables and tell people to use that one (or at least check what it is). could be called `SIRF_PYTHON_EXECUTABLE` or so.

Same for Matlab of course if multiple versions are installed.

what do people think?

**Comment by casperdcl** [comment]
https://stackoverflow.com/questions/29245558/how-to-link-with-python3-libs-with-cmake

**Comment by KrisThielemans** [comment]
possibly some confusion. My comment wasn't about CMake. I think we have that a bit better under control now by setting `PYTHON_EXECUTABLE` etc.

Instead, my comment is then afterwards, for the user of SIRF. They install everything properly, but then when they actually use it with the wrong python, it'll fail/crash in mysterious ways. Hope that clarifies this issue.

**Comment by casperdcl** [comment]
ah, I see. Well if they don't play around with multiple python versions, this shouldn't be a problem (like `travis` with `language: python`) otherwise, if they do, then they should be happy setting up the environments properly

**Comment by casperdcl** [comment]
I wouldn't override their `$PYTHON_EXECUTABLE` - might annoy people?

**Comment by KrisThielemans** [comment]
People often have multiple python versions, even if they don't know. especially on Mac (there's a half-broken system python, and the one installed by `brew` for instance). Or python 2 and python 3.

Agreed not to override `PYTHON_EXECUTABLE`. what about introducing `SIRF_PYTHON_EXECUTABLE` as I suggested?

**Comment by casperdcl** [comment]
yes, sounds fine to me

**Comment by KrisThielemans** [comment]
@paskino could you take care of this (for both Python and MATLAB), and also include it in the relevant documentation (the wiki currently?)

**Comment by paskino** [comment]
I think using conda would simplify. :D

I'll add $SIRF_PYTHON_EXECUTABLE to the env.

**Comment by KrisThielemans** [comment]
thanks. and MATLAB please. put it only in there if it's built. (might not be trivial)

**Comment by paskino** [comment]
Commits on 21st december ending with acf0be4190daddb7041890ca689a40badf86fc64 should close this.

**Comment by KrisThielemans** [comment]
yes indeed. thanks!
can you then add this to the documentation/wiki and close this issue?

**Comment by paskino** [comment]
Added references to these environement variables on the wiki 
https://github.com/CCPPETMR/SIRF/wiki/SIRF-and-MATLAB
and 
https://github.com/CCPPETMR/SIRF/wiki/SIRF-and-Python
