### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF-SuperBuild#74]
Documentation about Docker needed please!

**Comment by casperdcl** [comment]
https://github.com/CCPPETMR/SIRF-SuperBuild#installation-instructions-for-docker links to https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-on-Docker - let me know if you want something else.

**Comment by rijobro** [comment]
Thanks Casper. Might just be that Kris wanted it linked under Documentation that is on the home page of the Wiki. @KrisThielemans ?

**Comment by KrisThielemans** [comment]
done.
