### ISSUE TITLE
Build depends on system ACE

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF-SuperBuild#79]
Trying to install the SuperBuild on a CentOS7 machine the SuperBuild fails. 
The reason being that the dependency on [ACE ](http://www.cs.wustl.edu/~schmidt/ACE-overview.html)(Adaptive Communication Environment) cannot be satisfied. 

On ubuntu it seems to be available as system library and as a matter of facts it is in the dependency list for the VM.

1. How does it work on MacOS?
2. Should ACE be added to the dependencies we build with the SuperBuild?

**Comment by bathomas** [comment]
1 .`brew install ace` on macOS. 
2. Guess it should be a dependency, but also raises the question as to how many/which Linux distros to support.

**Comment by paskino** [comment]
The thing is that ACE is a not so standard package and it's not found in all the distros.

**Comment by KrisThielemans** [comment]
ACE should be in the dependency list for the SuperBuild (not the VM as you state), as well as others for Gadgetron. There seem to be RPM packages for CentOS as well.

Yes, it would be nice to add it to the SuperBuild, but [its build process](http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/ACE/ACE-INSTALL.html) is not quite "standard". They have an option to use [MPC](http://downloads.ociweb.com/MPC/docs/html/MakeProjectCreator.html) but that doesn't integrate with CMake as far as I can see. So, this becomes non-trivial.

We could potentially use a binary download (definitely on Windows), and use `make` on those where it is available.

In any case, for 1.0 we need to be clear that if they need Gadgetron, they need this.

**Comment by paskino** [comment]
I copy/paste an email from Ben
```
vagrant init centos/7
vagrant up
yum install git cmake wget unzip autoconf gcc-c++ mkdir src cd src wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.7.zip
unzip ACE-6.4.7
***wait forever!***
export ACE_ROOT=~/src/ACE_wrappers
cd ACE_wrappers/ace
ln -s config-linux.h config.h
cd ../include/makeinclude
ln -s platform_linux.GNU platform_macros.GNU cd ../../ace make
```

**Comment by paskino** [comment]
I believe this can be closed as it ACE is now in the external packages we can build.
