### ISSUE TITLE
how to pass options to projects

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#8]
Examples: 

- on the UCL CS CentOS system, we need to set `-DMKLROOT_PATH=` for Gadgetron's CMake as its MKL is too old (it will then use ACE).

- I'd like to be able to enable STIR_OPENMP for testing.

I guess, this can be done by first running "cmake .;make", then going into the relevant directory, running cmake-gui there and changing the configuration, but this seems rather painful.

**Comment by casperdcl** [comment]
you can also `cmake -DMKLROOT_PATH=... -DSTIR_OPENMP=1 && make` or just `cmake-gui` only (skip `cmake`) in the first place.

**Comment by KrisThielemans** [comment]
Would that ppass their from the superbuils cmake call to the project cmake call? I don't think so (at least without extra work)

________________________________

**Comment by casperdcl** [comment]
Yes, you're right - it would require a little extra work to pass through. I'm assuming we need something like [SIRF-SuperBuild:SuperBuild/External_STIR.cmake#L29-30](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/master/SuperBuild/External_STIR.cmake#L29-30)?

**Comment by KrisThielemans** [comment]
yes. that'd work. It's a bit inconvenient as it means we have to create all relevant options at the top-level I guess, but I suppose that makes some kind of sense, and doesn't seem arduous.

**Comment by KrisThielemans** [comment]
This link seems to give a mechanism to pass all cache variables
https://stackoverflow.com/questions/25533831/passing-cmake-variables-to-externalproject-add
I think we need something like this as we can never know which particular variables need to be passed on.

**Comment by KrisThielemans** [comment]
this has been (mostly) implemented a while ago.
