### ISSUE TITLE
error when using own build of boost

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#84]
at present, all travis builds have `USE_SYSTEM_BOOST=On`. should change that (now that we have ccache).

This will presumably be the same for SIRF.

Let's postpone this until Travis stuff and CMake has settled though.

**Comment by KrisThielemans** [comment]
I'd like to do this now as @bathomas had until quite recently a build failure when building boost ourselves (which is the default after all).
Let's do this for 1 build for Linux and 1 for OSX. obviously via a PR such that we can postpone it if really necessary.

**Comment by KrisThielemans** [comment]
thanks. It seems that this has uncovered the bug! When running CMake we get
```
 External project Boost has both BINARY_DIR and BUILD_IN_SOURCE!
```
@bathomas is that he same as what you saw?

**Comment by paskino** [comment]
I confirm that boost doesn't get built. WIP

**Comment by casperdcl** [comment]
feel free to work on this branch (`boost_build`) - I won't actually open a PR until it's fixed to avoid getting spam and excessive travis builds.

**Comment by bathomas** [comment]
Yes. That was it.

________________________________

**Comment by paskino** [comment]
I just managed to build Boost. However there is still this cosmetically horrible `Boost-prefix` directory in the build. Try to remove it.

**Comment by paskino** [comment]
I think it's fixed now.

**Comment by paskino** [comment]
@casperdcl I've pushed the fixes in the `boost_build` branch. I've tested on the VM and seem to work right. Do you create the PR?
