### ISSUE TITLE
travis osx python3

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF-SuperBuild#97]
build failing due to brew, probably easy to fix:

https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/344891590

**Comment by rijobro** [comment]
I think that for OSX with python3, this could be solved by replacing `brew install python3` with `brew upgrade python`

**Comment by KrisThielemans** [comment]
correct. there's probably more to it. However, I've recently fixed this in STIR. same should work here.
https://github.com/UCL/STIR/commit/616cb0f382fd8668dbc51f59a1603447b58d0582
