### ISSUE TITLE
self-host binary files from sourceforge

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF-SuperBuild#99]
sourceforge seems more and more unreliable. Now all our Travis jobs fail because
```
-- Using src='https://downloads.sourceforge.net/project/arma/armadillo-7.800.2.tar.xz'
-- [download 100% complete]
-- verifying file...
       file='/home/travis/build/CCPPETMR/SIRF-SuperBuild/downloads/Armadillo/armadillo-7.800.2.tar.xz'
-- MD5 hash of
    /home/travis/build/CCPPETMR/SIRF-SuperBuild/downloads/Armadillo/armadillo-7.800.2.tar.xz
  does not match expected value
    expected: 'c601f3a5ec6d50666aa3a539fa20e6ca'
      actual: 'cb530d737c8f2d1023797cf0587b4e05'
```
I saw the same on my own laptop (with `swigwin*zip`). Maybe we use the wrong URL for CMake, but downloading the files from a browser gives the correct checksum.

I think the best work-around is to self-host these files on our own website, although it's terrible of course. Or anyone has a better idea?

**Comment by KrisThielemans** [comment]
it's all working again so let;s see how this goes.

**Comment by paskino** [comment]
Sorry, I lost track of this. 
I guess we should review the files we need to host ourselves, which I presume may be the non git ones?

**Comment by KrisThielemans** [comment]
in principle everything on sourceforge, but let's wait and see (I've reassigned to 1.1) as it's an unsatisfactory solution.

**Comment by casperdcl** [comment]
we could upload the binaries to a public git repo

**Comment by KrisThielemans** [comment]
closing as it all seems fine recently.
